version: 8.4.1.{build}
image: Visual Studio 2017
configuration: Release
before_build:
  - nuget restore
build:
  project: EDDiscovery.sln
test_script:
  - nunit3-console EDDiscoveryTests\bin\Release\EDDiscoveryTests.dll --result=myresults.xml;format=AppVeyor
after_build:
  - cmd: copy EDDiscovery\bin\Release\EDDiscovery.Portable.zip EDDiscovery.Portable.zip
artifacts:
  - path: EDDiscovery.Portable.zip
cache:
  - packages -> **\packages.config
