version: 11.6.0.{build}
image: 
  - Visual Studio 2019
  - Ubuntu
configuration:
  - Debug
  - Release
install:
  - git submodule update --init
for:
-
  matrix:
    only:
      - image: Visual Studio 2019
        configuration: Release
  build:
    project: EDDiscovery.sln
  before_build:
    - nuget restore
  after_build:
    - cmd: copy EDDiscovery\bin\Release\EDDiscovery.Portable.zip EDDiscovery.Portable.zip
  artifacts:
    - path: EDDiscovery.Portable.zip
-
  matrix:
    only:
      - image: Visual Studio 2019
        configuration: Debug
  build:
    project: EDDiscovery.sln
  before_build:
    - nuget restore
-
  matrix:
    only:
      - image: Ubuntu
        configuration: Release
  before_build:
    - echo '<?xml version="1.0" encoding="utf-8"?><configuration><packageSources><add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" /></packageSources></configuration>' >~/.config/NuGet/NuGet.Config
    - nuget restore
  build_script:
    - msbuild /p:Configuration=Release EDDiscovery.sln /p:DefineConstants=NO_SYSTEM_SPEECH
-
  matrix:
    only:
      - image: Ubuntu
        configuration: Debug
  before_build:
    - echo '<?xml version="1.0" encoding="utf-8"?><configuration><packageSources><add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" /></packageSources></configuration>' >~/.config/NuGet/NuGet.Config
    - nuget restore
  build_script:
    - msbuild /p:Configuration=Debug EDDiscovery.sln "/p:DefineConstants=\"NO_SYSTEM_SPEECH;DEBUG;TRACE\""
cache:
  - packages -> **\packages.config
