version: 10.6.0.{build}
image:
  - Visual Studio 2017
  - Visual Studio 2019
configuration: Release
install:
  - git submodule update --init
before_build:
  - dotnet restore
build:
  project: EDDiscovery.sln
test_script:
  - dotnet test EDDiscoveryTests\Tests.csproj
for:
-
  matrix:
    only:
      - image: Visual Studio 2019

  after_build:
    - cmd: copy EDDiscovery\bin\Release\net461\EDDiscovery.Portable.zip EDDiscovery.Portable.vs2019.net461.zip
    - cmd: copy EDDiscovery\bin\Release\netcoreapp3.0\EDDiscovery.Portable.zip EDDiscovery.Portable.vs2019.netcore30.zip
  artifacts:
    - path: EDDiscovery.Portable.vs2019.net461.zip
    - path: EDDiscovery.Portable.vs2019.netcore30.zip
-
  matrix:
    only:
      - image: Visual Studio 2017

  after_build:
    - cmd: copy EDDiscovery\bin\Release\net461\EDDiscovery.Portable.zip EDDiscovery.Portable.zip
  artifacts:
    - path: EDDiscovery.Portable.zip
cache:
  - packages -> **\packages.config
